### ISSUE TITLE
Is this mod abandoned?

### ISSUE THREAD

**Issue by liach** [ModForgery/Tesla#6]
Just asking. Updated long ago.

**Comment by Rushmead** [comment]
ModForgery Split up a while ago. Most have gone their seperate ways

**Comment by modmuss50** [comment]
Yes it is sadly. sorry

**Comment by xbony2** [comment]
It more or less blew up in drama. Anyway, Tesla was very much a group effort, it doesn't belong to any one person. However, I propose we should relicense it under public domain, although I assume this requires the corporation of everyone who contributed.

**Comment by modmuss50** [comment]
I agree with this

**Comment by xbony2** [comment]
Sweet. I'd like to summon @klmDF14J @Mark-R-GitHub @Rushmead and @tattyseal

**Comment by tattyseal** [comment]
Not part of contributers, yet contributed. Explain.

**Comment by tattyseal** [comment]
Maybe one of us could undertake it as a project if everyone agrees?

**Comment by liach** [comment]
Sad story. And I hope this mod to be continued though.

**Comment by tattyseal** [comment]
@liach I would be happy to take it on, everyone would need to be in agreement and I'm not sure if that would happen

**Comment by tattyseal** [comment]
Also everyone forgot to summon @EwyBoy

**Comment by xbony2** [comment]
@tattyseal ideas.

If everyone agrees to make it PD, then anyone can take care of it.

**Comment by tattyseal** [comment]
Ok, so everyone that worked on it originally can?

**Comment by xbony2** [comment]
Ewy didn't appear to contribute code/art, according to [this](https://github.com/ModForgery/Tesla/graphs/contributors), which is why I didn't include him.

**Comment by xbony2** [comment]
Yeah, everyone in the link.

**Comment by tattyseal** [comment]
I just realised all he did was merge XD

**Comment by xbony2** [comment]
He did some design work I believe.

**Comment by tattyseal** [comment]
Well, a good idea would be give it like 3 months and if they don't contribute goto PR only for that person?

**Comment by xbony2** [comment]
I think most of us don't want to contribute anymore :P it's an older project, and older projects are usually boring.

**Comment by tattyseal** [comment]
I kinda want to do this now lol

**Comment by xbony2** [comment]
You're free to push to this repo if you want to :P

**Comment by xbony2** [comment]
Actually wait, that's a lie. I'll add you if you want.

**Comment by tattyseal** [comment]
I might redo it anyway

**Comment by xbony2** [comment]
Not like there's anything going on here though.

**Comment by Mark-R-GitHub** [comment]
I don't really care who takes it.

**Comment by klmDF14J** [comment]
Why not just leave it as it is and if people want to contribute then they can?

**Comment by xbony2** [comment]
@kimDF14J that would leave issues if anyone wanted to publish it.

**Comment by EwyBoy** [comment]
I'm out
